### ISSUE TITLE
Doesn't seem to claim any Nitro.

### ISSUE THREAD

**Issue by stanbeukers** [iLinked1337/AutoNitro#1]
Hey, So basically i tried the Claimer and i made a bot that sends a test Nitro gift. Now i checked the bot but it didn't log anything. Yeah that's it.

**Comment by quainthi** [comment]
because the nitro was invalid ofc lol.

**Comment by iLinked1337** [comment]
@quainthi is probably right, but just to make sure @stanbeukers send the gift you tested it with

**Comment by stanbeukers** [comment]
lol no. It should say: [ERROR]: Invalid nitro gift something like that

**Comment by stanbeukers** [comment]
Thats in the sln file

**Comment by iLinked1337** [comment]
oh yeah then it's just invalid. thank you for clarifying

**Comment by stanbeukers** [comment]
Okeh thanks
